### ISSUE TITLE
[Suggestion] Run before Wepack exit/quit

### ISSUE THREAD

**Issue by weblancaster** [rdoo/run-node-webpack-plugin#1]
Would be nice to have an option to run the script only before Webpack exit/quit. What do you think @rdoo ?

**Comment by rdoo** [comment]
What do you mean? It runs after Webpack compilation therefore its also before Webpack exit/quit. Give me a better explanation please

**Comment by weblancaster** [comment]
Never mind, I was trying to run the script at a stage that I did not really need. And you are right about the code running before it exits.

Thanks.
